version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb+srv://tejeshv11:tejeshv11@cluster0.haeee8a.mongodb.net/multi-level-comments

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
